
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    public int Category_Id { get; set; }

    public string Category_Name { get; set; }

    public byte[] Category_Image { get; set; }

    public System.DateTime Created_Date { get; set; }

    public int Created_User_Id { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_Id { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
