
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Invoice_Master = new HashSet<Invoice_Master>();

    }


    public int Customer_Id { get; set; }

    public int Customer_Code { get; set; }

    public string Customer_Name { get; set; }

    public string Customer_Contact { get; set; }

    public string Address { get; set; }

    public System.DateTime Created_Date { get; set; }

    public int Created_User_Id { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_id { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Master> Invoice_Master { get; set; }

}

}
