
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.Invoice_Details = new HashSet<Invoice_Details>();

        this.Purchase_Details = new HashSet<Purchase_Details>();

    }


    public int Product_ID { get; set; }

    public int Product_Code { get; set; }

    public string Product_Name { get; set; }

    public Nullable<int> Unit_ID { get; set; }

    public Nullable<int> Unit_In_Stock { get; set; }

    public Nullable<decimal> Unit_Cost { get; set; }

    public Nullable<decimal> Unit_Price { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public System.DateTime Created_Date { get; set; }

    public int Created_User_ID { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }

    public virtual Product_Unit Product_Unit { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Details> Purchase_Details { get; set; }

}

}
