
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase_Master
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Purchase_Master()
    {

        this.Purchase_Details = new HashSet<Purchase_Details>();

    }


    public int Purchase_Master_Id { get; set; }

    public Nullable<int> Supplier_Id { get; set; }

    public Nullable<decimal> Total_Amount { get; set; }

    public Nullable<bool> Purchase_Status { get; set; }

    public System.DateTime Created_Date { get; set; }

    public int Created_User_Id { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Details> Purchase_Details { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual Supplier Supplier1 { get; set; }

}

}
