
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase_Details
{

    public int Purchase_Product_Id { get; set; }

    public Nullable<int> Product_Id { get; set; }

    public Nullable<int> Purchase_Master_Id { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> Unit_Price { get; set; }

    public Nullable<decimal> Sub_Total { get; set; }

    public System.DateTime Created_Date { get; set; }

    public int Created_User_Id { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_Id { get; set; }



    public virtual Product Product { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Purchase_Master Purchase_Master { get; set; }

}

}
