
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_System
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {

        this.Purchase_Master = new HashSet<Purchase_Master>();

        this.Purchase_Master1 = new HashSet<Purchase_Master>();

    }


    public int Supplier_Id { get; set; }

    public int Supplier_Code { get; set; }

    public string Supplier_Name { get; set; }

    public string Supplier_Contact { get; set; }

    public string Supplier_Address { get; set; }

    public string Email { get; set; }

    public System.DateTime Created_date { get; set; }

    public int Created_User_Id { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public Nullable<int> Last_Modified_User_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Master> Purchase_Master { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Master> Purchase_Master1 { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
